//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit
    {
        public int debitID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> debitPersonID { get; set; }
        public Nullable<int> debitAdminID { get; set; }
        public string debitDate { get; set; }
    }
}
