//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Department { get; set; }
        public string Startofwork { get; set; }
        public string Birthday { get; set; }
        public int employeeID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    }
}
