//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public string productType { get; set; }
        public string productSeller { get; set; }
        public string productBrand { get; set; }
        public Nullable<int> productPrice { get; set; }
        public string productDate { get; set; }
        public Nullable<int> ProductState { get; set; }
    }
}
